[package]
name = "opensmtpd-filter-sake"
version = "0.1.0"
authors = ["Rodolphe Bréard <rodolphe@what.tf>"]
edition = "2021"
description = "Sub-address key filter for OpenSMTPD"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
